[pytest]
addopts = -v -s --tb=short
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: Smoke test cases
    regression: Regression test cases
    sanity: Sanity test cases
    login: Login related tests